<?php

namespace AppBundle\Repository;

/**
 * AuthorTabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorTabRepository extends \Doctrine\ORM\EntityRepository
{
}
