<?php

namespace AppBundle\Repository;

/**
 * BookTabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookTabRepository extends \Doctrine\ORM\EntityRepository
{
}
